# Настройка 
app:
  login: "" #Логином может быть номер телефона, почта, номер телефона должен быть в формате 7XXXXXXXXXX
  password: "" #Пароль от учетки
  delay: 10800 #Время задержки между апами в секундах
  #Время задержки будет добавляться случайным образом к delay для того чтобы быть более надежным и не привлекать внимание администрации платформы
  random_min_delay: 600 #Минимальное время задержки в секундах которая будет добавляться случайным образом
  random_max_delay: 1800 #Максимальное время задержки в секундах которая будет добавляться случайным образом